### ISSUE TITLE
hello!

### ISSUE THREAD

**Issue by hotarutomoe7** [phijor/SpecializeMii#4]
i wanted to ask you if you could resolve this problem with the program , when you use feed mii it crashed the game get you to home and reinicie the console when your using the gold pants , i was wondering and asking if you could fix out this issue please?

**Comment by quizque** [comment]
This is a issue to do with the console and not the app. He can not do anything but if you wanna play it you must un-gold your mii.

**Comment by hotarutomoe7** [comment]
theres no way to do anything to resolve it?

**Comment by quizque** [comment]
Besides to un-gold you mii, no there is no way to solve it. I had this issue too but just never played the game after that (It wasn't that good too be honest).

**Comment by hotarutomoe7** [comment]
ah ok well thanks :)

**Comment by phijor** [comment]
@nickthegamer5 is correct:

*Feed Mii* crashes when your personal Mii has gold pants; probably because of some programming oversight -- certainly none of the developers expected personal Miis to have gold pants. This something that cannot be fixed, because changes would need to be made to *Feed Mii* itself; sorry about that.

*SpecializeMii* only edits the data of your Mii by flipping a single bit; It cannot anticipate application that fail display valid Miis (which Miis with gold pants are). That's why it warns you before changing your personal Mii.

**Comment by hotarutomoe7** [comment]
Ah ok then even if i deleite it and re install will no work right ?

Enviado desde mi iPhone

El 25/02/2017, a las 9:28 a.m., phijor <notifications@github.com<mailto:notifications@github.com>> escribió:


Closed #4<https://github.com/phijor/SpecializeMii/issues/4>.
